:sparkles: 픽업 주문 API 및 Test Code
lotteon2/BB-ORDER-SERVICE pull request #12
Opened 2023-12-18 09:47 UTC by binarywoo27

## 개요

## PR 유형
어떤 변경 사항이 있나요? ✅

| ✅ | content|
|:--:|:--|
| ✅  |새로운 기능 추가|
|   |버그 수정|
|   |CSS 등 사용자 UI 디자인 변경|
|   |코드에 영향을 주지 않는 변경사항(오타 수정, 탭 사이즈 변경, 변수명 변경)|
| ✅  |코드 리팩토링|
|   |주석 추가 및 수정|
|   |문서 수정|
|  ✅ |테스트 추가, 테스트 리팩토링|
|   |빌드 부분 혹은 패키지 매니저 수정|
|   |파일 혹은 폴더명 수정|
|   |파일 혹은 폴더 삭제|

## 스크린 샷

## PR Checklist
PR이 다음 요구 사항을 충족하는지 확인하세요.

- [ ] local에서 실행되는 것을 확인 했나요?
- [ ] 변경 사항에 대해 테스트를 통과했나요?
- [ ] 설계와 관련된 변경 사항을 공유했나요? (api 스펙, entity 등)

2023-12-18 10:48 UTC, qwerty1434 requested changes
코멘트 확인 부탁드립니다~! 😊

2023-12-18 10:48 UTC, qwerty1434 commented on src/main/java/kr/bb/order/config/RedisConfig.java
> +    redisTemplate.setValueSerializer(new StringRedisSerializer());
value가 아니라 key인거 같습니다 :)

2023-12-18 10:48 UTC, qwerty1434 commented on src/main/java/kr/bb/order/dto/request/store/ProcessOrderDto.java
> +    List<Long> couponIds = new ArrayList<>();
List의 static메서드인 of를 써보는건 어떨까요. 불변이라 더 안전한걸로 알고있습니다

2023-12-18 10:48 UTC, qwerty1434 commented on src/main/java/kr/bb/order/service/OrderService.java
> +    productServiceClient.validatePrice(priceCheckDtos).getData();
getData를 하는 이유가 궁금합니다

2023-12-18 10:48 UTC, qwerty1434 commented on src/main/java/kr/bb/order/service/OrderService.java
> +    boolean isSubscriptionPay = false;
저였으면 static final 변수로 선언했을거 같습니다

2023-12-18 10:48 UTC, qwerty1434 commented on src/main/java/kr/bb/order/service/OrderService.java
> +      processOrderDelivery(processOrderDto, orderInfo);
내부호출!!

2023-12-19 00:35 UTC, binarywoo27 commented on src/main/java/kr/bb/order/dto/request/store/ProcessOrderDto.java
> +    List<Long> couponIds = new ArrayList<>();
꿀팁 감사합니다

2023-12-19 02:54 UTC, binarywoo27 commented on src/main/java/kr/bb/order/service/OrderService.java
> +    productServiceClient.validatePrice(priceCheckDtos).getData();
getData를 제거하여 수정하였습니다. 추후에 feign통신시 exception handling 도 추가하도록 하겠습니다!

2023-12-19 07:14 UTC, qwerty1434 approved these changes
확인했습니다 😊

2023-12-19 07:17 UTC, merged